In [2]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [3]:
mp_key = "CZceLJ3kGnm9d5zpfdqDbLaL8n671YIQ"
mp_id = "mp-961711"

In [4]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [47]:
view = quick_view(conv_struc)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [48]:
sym = SpacegroupAnalyzer(conv_struc).get_symmetry_operations()

#Atomes sélectionnés
Zr = [0.5,0,0]
Si = [1,0,1]
Pt = [0.75,0.75,0.25]



S1 = sym[1]
S2 = sym[6]
S3 = sym[9]


Zr_sym = S1.operate(Zr)
Si_sym = S2.operate(Si)
Pt_sym = S3.operate(Pt)

In [52]:
print("L'atome de départ a comme coordonnées: {}\n".format(Zr))

print("L'opération est une symétrie centrale par rapport au point origine. \n")
print(S1, "\n")

print("L'opération se calcule donc de la façon suivante : \n")
print(S1.rotation_matrix, "*", Zr, '+', S1.translation_vector, "\n")

print("L'atome d'arrivé a comme coordonnées : {}\n".format(Zr_sym))

#Représentation selon jupyter-jsmol
view = quick_view(conv_struc,supercell=[1,1,1])
display(view)
view.script('draw symop 2 {atomno = 4}; select atomno=4; label on; color red')

L'atome de départ a comme coordonnées: [0.5, 0, 0]

L'opération est une symétrie centrale par rapport au point origine. 

Rot:
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

L'opération se calcule donc de la façon suivante : 

[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]] * [0.5, 0, 0] + [0. 0. 0.] 

L'atome d'arrivé a comme coordonnées : [ 0.  -0.5  0. ]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [53]:
print("L'atome de départ a comme coordonnées: {}\n".format(Si))

print("L'opération est une rotation de 90 degrés dans le plan xy. \n")
print(S2, "\n")

print("L'opération se calcule donc de la façon suivante : \n")


print(S2.rotation_matrix, "*", Si, '+', S2.translation_vector, "\n")

print("L'atome d'arrivé a comme coordonnées : {}\n".format(Si_sym))

#Représentation selon jupyter-jsmol
view = quick_view(conv_struc,supercell=[1,1,1])
display(view)
view.script('draw symop 7 {atomno = 1}; select atomno=1; label on; color red')

L'atome de départ a comme coordonnées: [1, 0, 1]

L'opération est une rotation de 90 degrés dans le plan xy. 

Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

L'opération se calcule donc de la façon suivante : 

[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]] * [1, 0, 1] + [0. 0. 0.] 

L'atome d'arrivé a comme coordonnées : [-1.  0. -1.]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [55]:
print("L'atome de départ a comme coordonnées: {}\n".format(Pt))

print("L'opération est une symétrie miroir par rapport au plan yz. \n")
print(S3, "\n")

print("L'opération se calcule donc de la façon suivante : \n")

print(S3.rotation_matrix, "*", Pt, '+', S3.translation_vector, "\n")

print("L'atome d'arrivé a comme coordonnées : {}\n".format(Pt_sym))

#Représentation selon jupyter-jsmol
view = quick_view(conv_struc,supercell=[1,1,1])
display(view)
view.script('draw symop 10 {atomno = 22}; select atomno=22; label on; color red')

L'atome de départ a comme coordonnées: [0.75, 0.75, 0.25]

L'opération est une symétrie miroir par rapport au plan yz. 

Rot:
[[ 0.  0. -1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
tau
[0. 0. 0.] 

L'opération se calcule donc de la façon suivante : 

[[ 0.  0. -1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]] * [0.75, 0.75, 0.25] + [0. 0. 0.] 

L'atome d'arrivé a comme coordonnées : [-0.25  0.75 -0.75]



JsmolView(layout=Layout(align_self='stretch', height='400px'))